export const TASK_SUCCESS = "TASK_SUCCESS";
export const TASK_REMOVE = "TASK_REMOVE";
export const TASK_LOAD = "TASK_LOAD";
export const TASK_CLOSE_SNACK = "TASK_CLOSE_SNACK";
export const TASK_FETCH_LOCAL_STORAGE = "TASK_FETCH_LOCAL_STORAGE";